build: Add missing includes for LLVM 10
Fixes:

[ 50%] Building CXX object analyses/CMakeFiles/PredatorPlugin.dir/predator_plugin.cpp.o
In file included from /sbt-instrumentation/analyses/predator_plugin.cpp:1:
/sbt-instrumentation/analyses/predator_plugin.hpp: In constructor ‘PredatorPlugin::PredatorPlugin(llvm::Module*)’:
/sbt-instrumentation/analyses/predator_plugin.hpp:93:15: error: ‘errs’ is not a member of ‘llvm’
   93 |         llvm::errs() << "PredatorPlugin: Running Predator...\n";
      |               ^~~~